//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int question_id { get; set; }
        public int difficulty_id { get; set; }
        public int category_id { get; set; }
        public string question { get; set; }
        public string correct_answer { get; set; }
        public string answer_1 { get; set; }
        public string answer_2 { get; set; }
        public string answer_3 { get; set; }
        public Nullable<int> question_type { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Difficulty Difficulty { get; set; }
    }
}
