//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string nickname { get; set; }
        public string password { get; set; }
        public byte[] avatar { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> rating2vs2 { get; set; }
        public Nullable<int> NumberOfAnswers { get; set; }
        public Nullable<int> NumberOfCorrectAnswers { get; set; }
        public Nullable<int> NumberOfGames { get; set; }
        public Nullable<int> NumberOfGamesWon { get; set; }
        public string BestCategory { get; set; }
    }
}
